$(document).ready(function(){$("#code_hot dl:first").addClass("dropList-hover");$("#code_hot dl").mouseover(function(){$("#code_hot dl.dropList-hover").removeClass("dropList-hover");$(this).addClass("dropList-hover")});$(".shop-evaluation-label label").on("click",function(){var a=$(this).attr("data").split("|");$(".shop-evaluation-score p").each(function(b){$(this).html(a[b])})});0<$(".shop_nav a").length&&0<$(".shop_nav a[href='"+location.href+"']").length&&$(".shop_nav a[href='"+location.href+"']").addClass("cur");
$("#shop_search").click(function(){var a="";$(this).closest("div").find(":text").each(function(){""!=$(this).val()&&(a+=$(this).attr("name")+"/"+$(this).val()+"/")});if(""==a)return layer.alert("\u4eb2\uff0c\u81f3\u5c11\u9700\u8981\u8f93\u51651\u9879\u641c\u7d22\u5185\u5bb9\uff01",{icon:0},function(a){$("#shop_key").focus();layer.close(a)}),!1;location.href=$("input:radio[name='good_type']:checked").val()+a});$("#sobid").click(function(){var a=$(this).closest("ul").find(":text");if(""==a.val())return layer.alert("\u4eb2\uff0c\u8bf7\u8f93\u5165\u8981\u641c\u7d22\u7684\u6295\u6807\u53f7\uff01",
{icon:0},function(b){a.focus();layer.close(b)}),!1;selist(0,Number(a.val()));$("#sobid_reset").show();$("#sobid_reset,.filter-comment label").click(function(){$(".bid_tit :text").val("");$("#sobid_reset").hide();"sobid_reset"==$(this).attr("id")&&selist()})});$(".cartadd").click(function(){var a=$(this).attr("id");Aform("cartadd","action="+$(this).attr("data")+"&info="+$(this).attr("info"),function(b){if(-2==b.state&&"undefined"==typeof b.info)return layer_login("\u518d\u7ee7\u7eed",a),!1;Rs(b)})});
$(".report").click(function(){layer.load();$.get("/html/report",{good:$(this).attr("good"),number:$(this).attr("number")},function(a){layer_ly(a,!1,!0,"680px")})});$(".list .dlist").mouseenter(function(){var a=$(this);enter=setTimeout(function(){a.css("border","1px solid #ff4400").find(".Layer").show()},500)}).mouseleave(function(){clearTimeout(enter);$(this).css("border","1px solid #e5e5e5").find(".Layer").hide()});$(".list .slist").hover(function(){$(this).addClass("slcur")},function(){$(this).removeClass("slcur")});
$(".tlist ul,.tasklist ul").hover(function(){$(this).addClass("curr")},function(){$(this).removeClass("curr")});$(".fw_a").hover(function(){$(this).addClass("fw_on");$(this).siblings().removeClass("fw_on");var a=$(".fw_a").index($(this));$(".fw_txt cite").hide();$(".fw_txt cite").eq(a).show();$(this).hasClass("tpay")&&$(this).find("i").html("&#xe659;")},function(){if(!$(this).hasClass("tpay"))return!1;$(".fw_txt cite").hide();$(this).removeClass("fw_on");$(this).find("i").html("&#xe658;")})});
$(".upbid").live("click",function(){var a=$(this).attr("id");$.post("/html/upbid",{number:a},function(b){if(-2==b)return layer_lp("\u67e5\u770b\u7edf\u8ba1",a),!1;layer_ly(b," ",!1)})});
$(".outbid").live("click",function(){var a=$(this);layer.confirm("<b>\u60a8\u786e\u5b9a\u8981<font color=red>\u6dd8\u6c70\u6b64\u6807</font>\u5417\uff1f</b><br><font color=#999999>\u6dd8\u6c70\u540e\u8be5\u6295\u6807\u65e0\u6cd5\u518d\u4fee\u6539\u548c\u9009\u4e2d\u6807\uff01</font>",{icon:3},function(b){Aform("outbid","number="+a.attr("number"),function(b){1==b.state?a.closest("li").empty().closest("dt").find(".bicon").html('<i class="out"><font style="font-size:16px;">&#xe64b;</font>\u6dd8\u6c70</i>'):
Rs(b)});layer.close(b)})});$(".sobid").live("click",function(){scTop(".layui-form");$("input[name=sobid]").val($(this).html());$("#sobid").click()});$(".computing_act i:not(.no)").live("click",function(){var a=$("#p_number").val(),b=1;"sub"==$(this).attr("data")&&(b=-1);a=parseInt(a)+b;$("#p_number").val(a);1>=a?$(".computing_act i[data='sub']").addClass("no"):$(".computing_act i[data='sub']").removeClass("no")});
$("#p_down,#p_up").live("click",function(){var a=$(this).attr("class"),b=$(this).attr("id"),d=parseInt($(".curPage").html());"no"!=a&&($(".small_pages input[type=text]").val(""),gelist("p_up"==b?d-1:d+1))});$(".gopage").live("click",function(){var a=$(this).prev().val();a>parseInt($(".totalPage").html())?layer.alert("\u4e0d\u80fd\u8d85\u8fc7\u6700\u5927\u9875\u6570\uff1a"+$(".totalPage").html(),{icon:0}):1>a?layer.alert("\u4e0d\u80fd\u4f4e\u4e8e\u6700\u5c0f\u9875\u6570\uff1a1",{icon:0}):gelist(a)});
function set_cur(a){$(".c_r_menu em").hasClass("cur")&&$(".c_r_menu em").removeClass("cur");$(".c_r_menu em"+a).addClass("cur")}function getPageBar(a,b){$("#p_up,#p_down").addClass("no");1<a&&$("#p_up").removeClass("no");a<b&&$("#p_down").removeClass("no")}$(".IRadio label").live("click",function(){$(this).closest(".IRadio").find("label.IChecked").removeClass("IChecked");$(this).addClass("IChecked")});$(".filter-comment label").live("click",function(){selist()});
function shopso(){if(0>=$('.list_tab :text[value!=""]').length)return layer.alert("\u4eb2\uff0c\u641c\u7d22\u5173\u952e\u8bcd\u4e0d\u80fd\u4e3a\u7a7a\uff01",{icon:0},function(a){$("#keys").focus();layer.close(a)}),!1;var a=window.location.pathname.split("/"),b=$.inArray("page",a);0<b&&a.splice(b,2);$.each($('.list_tab :text[data!=""]'),function(b,c){b=$(c).attr("data");c=$.trim($(c).val());var e=$.inArray(b,a);""==c?0<e&&a.splice(e,2):0<e?a[e+1]=c:a.push(b,c)});console.log(a);a=$.grep(a,function(a){return 0<
a.length});$url=a.join("/");location.href="/"+$url}
gelist=function(a,b,d){a=a||0;1<a&&scTop("#c_bb",45);$.ajax({type:"POST",url:"/Apage/",async:!0,data:"list=geva&pro="+readmeta("Item-Number")+"&good="+readmeta("Pg-Type")+"&page="+a,dataType:"json",success:function(a){$.each(a,function(a,b){$("."+a).empty();$("."+a).html(b)});getPageBar(a.curPage,a.totalPage);$(".c_r_menu").menu_layer();layer_photos()},error:function(){layer.msg("\u52a0\u8f7d\u5931\u8d25\uff0c\u8bf7\u91cd\u8bd5\uff01");layer.close(loading);return!1}})};
selist=function(a,b){a=a||0;var d=readmeta("Pg-Type");b=b||$(".filter-comment .IChecked").attr("data");1<a&&scTop("#shop_pg_scTop",140);$.ajax({type:"POST",url:"/Apage/",async:!0,data:"list="+d+"&bh="+readmeta("Item-Number")+"&filter="+b+"&page="+a,dataType:"json",success:function(a){$.each(a,function(a,b){$("."+a).empty();$("."+a).html(b)});"bid"!=d?layer_photos():getPageBar(a.curPage,a.totalPage)},error:function(){layer.msg("\u52a0\u8f7d\u5931\u8d25\uff0c\u8bf7\u91cd\u8bd5\uff01");return!1}})};$.fn.extend({layer_top:function(){var a=$("#layer_top").offset().top+40;$(window).scroll(function(){$(window).scrollTop()>a?$("#layer_top").addClass("topsp"):$("#layer_top").removeClass("topsp")})}});
$.fn.extend({menu_layer:function(){var a=$("#c_aa").offset().top,b=$("#c_bb").offset().top,d=$("#c_cc").offset().top;$(window).scroll(function(){var c=$(this).scrollTop()+46;c>=d?set_cur(".c_cc"):c>=b?set_cur(".c_bb"):c>=a&&set_cur(".c_aa")});$(".c_r_menu em").click(function(){var a=$(this).attr("class");$("body").scrollTop($("#"+a.replace(/cur/,"")).offset().top-43);$(this).addClass("cur").siblings("em").removeClass("cur")})}});